services:
  - type: web
    name: axiom
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/Nonarkara/Axiom
    branch: main
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
