import { createHash, timingSafeEqual } from 'node:crypto';
import { readFileSync } from 'node:fs';

export class HttpError extends Error {
  constructor(statusCode, message) {
    super(message);
    this.statusCode = statusCode;
  }
}

export function securityHeaders() {
  const html = readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
  const hashes = [...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)]
    .filter((match) => !/\bsrc\s*=/i.test(match[1]))
    .map((match) => `'sha256-${createHash('sha256').update(match[2]).digest('base64')}'`);
  return {
    'Content-Security-Policy': [
      "default-src 'self'",
      `script-src 'self' ${hashes.join(' ')} https://unpkg.com https://static.cloudflareinsights.com`,
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com",
      "font-src 'self' https://fonts.gstatic.com",
      "img-src 'self' data: blob: https://server.arcgisonline.com https://unpkg.com",
      "connect-src 'self' https://cloudflareinsights.com",
      "object-src 'none'",
      "base-uri 'none'",
      "frame-ancestors 'none'",
      "form-action 'self'",
    ].join('; '),
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
    'Strict-Transport-Security': 'max-age=31536000',
  };
}

export function renderPagesHeaders() {
  return `# Generated by scripts/security-headers.mjs; regenerate after editing inline scripts.\n/*\n${Object.entries(securityHeaders()).map(([name, value]) => `  ${name}: ${value}`).join('\n')}\n\n/admin/*\n  Cache-Control: no-store\n  X-Robots-Tag: noindex, nofollow\n\n/data/evidence-snapshot.json\n  Cache-Control: no-store\n`;
}

export function isAdminPath(pathname) {
  return /^\/(?:admin(?:\/|$)|api\/admin(?:\/|$)|api\/analytics\/summary(?:\/|$))/i.test(pathname);
}

function digest(value) {
  return createHash('sha256').update(value).digest();
}

export function createRequestGuard({ username = 'admin', password = '' } = {}) {
  const failures = new Map();
  const pageviews = new Map();
  const expected = digest(`${username}:${password}`);

  function consume(map, key, maximum) {
    const now = Date.now();
    // The listener uses real socket addresses, never spoofable forwarding headers.
    for (const [address, bucket] of map) {
      if (bucket.until <= now) map.delete(address);
    }
    if (!map.has(key)) {
      if (map.size >= 1024) throw new HttpError(429, 'Too many requests');
      map.set(key, { count: 0, until: now + 60_000 });
    }
    const bucket = map.get(key);
    if (++bucket.count > maximum) throw new HttpError(429, 'Too many requests');
  }

  return function guard(req, res, pathname, listenPort) {
    const host = req.headers.host;
    const allowedHosts = [`127.0.0.1:${listenPort}`, `localhost:${listenPort}`];
    if (!allowedHosts.includes(host)) throw new HttpError(403, 'Untrusted host');

    const protectedPath = isAdminPath(pathname);
    const mutation = !['GET', 'HEAD', 'OPTIONS'].includes(req.method);
    if (protectedPath || mutation) {
      const origin = req.headers.origin;
      if ((origin && origin !== `http://${host}`) || req.headers['sec-fetch-site'] === 'cross-site') {
        throw new HttpError(403, 'Cross-site request blocked');
      }
    }

    if (protectedPath) {
      res.setHeader('Cache-Control', 'no-store');
      res.setHeader('X-Robots-Tag', 'noindex, nofollow');
      if (password.length < 16 || !username || /[:\r\n]/.test(username)) {
        throw new HttpError(503, 'Admin disabled: configure AXIOM_ADMIN_PASSWORD (at least 16 characters).');
      }
      const authorization = req.headers.authorization || '';
      const match = authorization.match(/^Basic ([A-Za-z0-9+/]+={0,2})$/i);
      const supplied = match ? Buffer.from(match[1], 'base64').toString('utf8') : '';
      if (!timingSafeEqual(digest(supplied), expected)) {
        consume(failures, req.socket.remoteAddress, 20);
        res.setHeader('WWW-Authenticate', 'Basic realm="Axiom local admin", charset="UTF-8"');
        throw new HttpError(401, 'Authentication required');
      }
    }
    if (pathname === '/api/pageview' && req.method === 'POST') {
      consume(pageviews, req.socket.remoteAddress, 60);
    }
  };
}

export async function readJsonBody(req) {
  if (!/^application\/json(?:\s*;|\s*$)/i.test(req.headers['content-type'] || '')) {
    throw new HttpError(415, 'Content-Type must be application/json');
  }
  const rawBody = await new Promise((resolve, reject) => {
    const chunks = [];
    let total = 0;
    let oversized = false;
    req.on('data', (chunk) => {
      total += chunk.length;
      if (total > 1024 * 1024) {
        if (!oversized) reject(new HttpError(413, 'Request body too large'));
        oversized = true;
        chunks.length = 0;
      } else if (!oversized) {
        chunks.push(chunk);
      }
    });
    req.on('end', () => {
      if (!oversized) resolve(Buffer.concat(chunks).toString('utf8'));
    });
    req.on('error', reject);
    req.on('aborted', () => reject(new HttpError(400, 'Request aborted')));
  });
  let body;
  try {
    body = JSON.parse(rawBody);
  } catch {
    throw new HttpError(400, 'Invalid JSON');
  }
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    throw new HttpError(400, 'JSON body must be an object');
  }
  return body;
}

export function cleanPublicUrl(value) {
  if (value === undefined || value === null || value === '') return null;
  if (typeof value !== 'string' || value.length > 2048) throw new HttpError(400, 'Invalid URL');
  const text = value.trim();
  if (!text) return null;
  let url;
  try {
    url = new URL(text);
  } catch {
    throw new HttpError(400, 'URL must be an absolute HTTP or HTTPS address');
  }
  if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) {
    throw new HttpError(400, 'URL must be an HTTP or HTTPS address without credentials');
  }
  return url.href;
}
